E_Mart/E_Mart/urls.py
from django.contrib import admin
from django.urls import path,include
from Home_Module import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home_Module.urls')),
    path('shipping/',include('shipping.urls')),
    path('order/',include('order.urls')),
    path('accounts/',include('allauth.urls')),	
    path('activate/<uidb64>/<token>',views.Verification.as_view(),name="activate"),
    path('reset_password/<uidb64>/<token>',views.reset_password,name="reset_password"),
    
   
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

E_Mart/order/urls.py
from django.urls import path
from . import views
app_name="order"
urlpatterns=[
            path('myorders/',views.my_orders,name="my_orders"),
            path('order_details/<int:id>/',views.order_details,name="order_details"),
            path('order_delivered/<int:id>/',views.order_delivered,name="order_delivered"),
            path("orders/",views.seller_orders,name="seller_orders"),
            path('seller_order_details/<int:id>/',views.seller_orders_details,name="seller_orders_details"),
            path('seller_confirmation/<int:id>/',views.seller_confirmation,name="seller_confirmation")
]

E_Mart/order/models.py
from django.db import models
from Home_Module.models import User,Products

# Create your models here.
class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name="order_user")
    is_shipped=models.BooleanField(default=False)
    date=models.DateTimeField(verbose_name="placed on",auto_now_add=True)
    is_delivered=models.BooleanField(verbose_name="status",default=False)
    bill=models.PositiveIntegerField(default=0)
    

    def __str__(self):
        return f'{self.id}'
class OrderDetails(models.Model):
    products=models.ForeignKey(Products,on_delete=models.CASCADE,related_name="product")
    qty=models.PositiveIntegerField()
    order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name="order")
    is_shipped=models.BooleanField(verbose_name="shipped",default=False)

E_Mart/order/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from Home_Module.utility_functions import isUserLogin,permission_check
from django.shortcuts import render,redirect,reverse
from .models import Order,OrderDetails
from Home_Module.models import Products,Cart
from django.contrib import auth,messages
from django.db.models import Q
# Create your views here.
def my_orders(request):
   user=permission_check(request)
   if user is None:
      return redirect(reverse("Home_Module:signup"))
   if request.method=="GET":
      orders=Order.objects.filter(user=user).order_by('-date')
      cart=Cart.objects.filter(user=user)  #cart-notification
      return render(request,"order/orders.html",{"user":user,"orders":orders,"notify":len(cart)})
def order_details(request,id):
   user=permission_check(request)
   if user is None:
      return redirect(reverse("Home_Module:signup"))
   if request.method=="GET":
      cart=Cart.objects.filter(user=user)   #cart-notification
      order_details=OrderDetails.objects.filter(order=id)
      return render(request,"order/order_details.html",{"user":user,"orders_details":order_details,"notify":len(cart),"variable":"base.html"})
    
def order_delivered(request,id):
   user=permission_check(request)
   if user is None:
      return redirect(reverse("Home_Module:signup"))
   if request.method=="GET":
      try:
         order=Order.objects.get(id=id)
         order.is_delivered=True
         order.save()
         messages.info(request,"You have confirmed that you have received the order.Hope you like it")
         return redirect(reverse("order:my_orders"))
      except Order.DoesNotExist:
         messages.warning(request,"This order doesn't exist.Perhaps it has been deleted")
         return redirect(reverse("order:my_orders"))
         
def seller_orders(request):
   user=isUserLogin(request,'seller')
   if user is None:
      return redirect(reverse("Home_Module:seller_center"))
   if request.method=="GET":
      p=Products.objects.filter(sellerId=user)
      ordersDetails=OrderDetails.objects.filter(products__in=p)
      ids=[]
      confirmation={}
      for order in ordersDetails:
         ids.append(order.order.id)
         if order.is_shipped:
            confirmation[order.order.id]=True

      orders=Order.objects.filter(pk__in=ids).order_by('-date')
      return render(request,"order/seller_orders.html",context={"user":user,"orders":orders,"confirmation":confirmation})
def seller_orders_details(request,id):
   user=isUserLogin(request,'seller')
   if user is None:
      return redirect(reverse("Home_Module:seller_center"))
   if request.method=="GET":
      p=Products.objects.filter(sellerId=user)
      order_details=OrderDetails.objects.filter(Q(products__in=p),Q(order=id) )

      return render(request,"order/order_details.html",{"user":user,"orders_details":order_details,"variable":f"Seller_Module/Seller_base.html"})
def seller_confirmation(request,id):
   user =isUserLogin(request,'seller')
   if user is None:
      return redirect(reverse("Home_Module:seller_center"))
   if request.method=="GET":
      p=Products.objects.filter(sellerId=user)
      order_details=OrderDetails.objects.filter(order=id)
      order_details_for_this_user=order_details.filter(products__in=p).update(is_shipped=True)
      count=order_details.filter(is_shipped=False).count()
      if count==0:
         try:
            Order.objects.filter(pk=id).update(is_shipped=True)
         except Order.DoesNotExist:
            messages.warning(request,"This order doesn't exist.Perhaps it has been deleted")
      return redirect(reverse("order:seller_orders"))

E_Mart/order/templates/order/order_details.html
{%extends variable %}
{% load static %}
{%block css%}
<link rel="stylesheet" href="{%static '/css/shipping/orders.css'%}"/>
<link rel="stylesheet" href="{%static '/css/home/cart.css'%}"/>
{%endblock%}
{%block body%}
<div class="order">
<div class="small-container cart-page">
<div class="col-lg-12 ">
    {%for order_detail in orders_details%}
			<div class=" box-element">
				<div class="cart-row">
					<div style="flex:2"><strong>Product</strong></div>
                    <div style="flex:2"><strong>Product-Name</strong></div>
                    <div style="flex:2"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				

				<div class="cart-row">
					<input type="hidden" id="hidden"  value={{order_detail.id}} > 
					
					<div style="flex:2"><p><img class="cart-row-image" src="{{order_detail.products.image1.url}}"></p> </div>
                    <div style="flex:2">
						<p>{{order_detail.products}}</p>
					</div>
					<div style="flex:2" ><p id="p{{order_detail.id}}">{{order_detail.products.price}}</p></div>
                    <div style="flex:1">
						<p id="qty{{order_detail.id}}" class="quantity">{{order_detail.qty}}</p>
					</div>
                    <div style="flex:1">
						<p id="sub{{order_detail.id}}"></p>
					</div>
				</div>
			</div>
			<br>
			{%endfor%}
		</div>
		
	</div>
    </div>
</div>
{%endblock%}
{%block js%}
<script src="{%static  'javascript/home/orders.js' %}"></script>
{%endblock%}
	  

E_Mart/order/templates/order/orders.html
{%extends '../base.html'%}
{% load static %}
{%block css%}
<link rel="stylesheet" href="{%static '/css/shipping/orders.css'%}"/>
<link rel="stylesheet" href="{%static '/css/home/cart.css'%}"/>
{%endblock%}
{%block body%}
<div class="order">
<div class="container cart-page">
		{%for order in orders%}
		<div class="col-lg-12">
			<div class="box-element">
                <div class="cart-row2">
					<div style="flex:1;color:blue"><strong style="color:gray">Bill:</strong>{{order.bill}}</div>
					<div style="flex:2;color:blue"><strong style="color:gray">Order Place On:</strong>{{order.date}}</div>
					
				</div>
				<div class="cart-row">
					<div style="flex:2"><strong>Oreder ID</strong></div>
					<div style="flex:1"><strong>Status</strong></div>
					<div style="flex:1"><strong>Recieved Or Not?</strong></div>
				</div>

				<div class="cart-row">
					<div style="flex:2"><a href="{%url 'order:order_details' order.id%}"><p>{{order.id}}</p></a></div>

					{%if order.is_delivered%}
						<div style="flex:1">Finished</p></a></div>
						<div style="flex:1">Buyer has confirmed order received</div>
					{%elif order.is_shipped%}
						<div style="flex:1"><p>Your order is on the way</p></div>
						<div style="flex:1"><a onclick="return confirm_order()"  class="orders-btn " href="{%url 'order:order_delivered' order.id%}">Recieved?</a></div>
					{%else%}
						<div style="flex:1"><p>we are preparing your order</p></div>
						<div style="flex:1"><p></p></div>
					{%endif%}
				</div>
			</div>
			<br>
		</div>
        {%endfor%}
    </div>
</div>
{%endblock%}

E_Mart/order/templates/order/seller_orders.html
{%extends '../Seller_Module/Seller_base.html'%}
{% load static %}
{%block css%}
<link rel="stylesheet" href="{%static '/css/seller/AllProduct.css'%}"/>
{%endblock%}
{%block body%}
<div class="small-container cart-page">
<table>
    <thead>
        <tr>
            <th>order id</th>
            <th>Date</th>
            <th>Customer</th>
            <th>status</th>
            <th>Confirmation</th>

        </tr>
    </thead>    
    {%for order in orders%}
        <tr>
            <td><a href="{%url 'order:seller_orders_details' order.id%}" >{{order.id}}</a></td>
            <td>{{order.date}}</td>
            <td>{{order.user}}</td>
            {%if order.is_delivered%}
                <td>Customer has received the order </td>
            {%elif order.is_shipped%}
                <td>Order has been Shipped </td>
            {%else%}
                <td>Initial</td>
            {%endif%}
            {%if order.id in confirmation%}
                <td>Seller has confimed order Shipped</td>
            {%else%}
                <td><a onclick="return confirm_order()" href="{%url 'order:seller_confirmation' order.id%}" >confirm order Shipped</a></td>
            {%endif%}
        
        </tr>
       
    {%endfor%}


</table>
</div>
{%endblock%}