E_Mart/E_Mart/urls.py
from django.contrib import admin
from django.urls import path,include
from Home_Module import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home_Module.urls')),
    path('shipping/',include('shipping.urls')),
    path('order/',include('order.urls')),
    path('accounts/',include('allauth.urls')),	
    path('activate/<uidb64>/<token>',views.Verification.as_view(),name="activate"),
    path('reset_password/<uidb64>/<token>',views.reset_password,name="reset_password"),
    
   
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

E_Mart/Home_Module/urls.py
from django.urls import path
from .import views,Seller_views
from django.contrib.auth import views as auth_views
app_name='Home_Module'
urlpatterns=[
    path('',views.home,name="home"),
    path('login/', views.login,name="login"),
    path('signup/',views.signup,name="signup"),
    path('forget',views.forget,name="forget"),
    path('customer/',views.cust_api,name="cust_api"),
    path('customer/username=<str:name>',views.cust_api,name="cust_api"),
    path('customer/email=<str:email>',views.cust_api,name="cust_api"),
    path('contact',views.contact,name="contact"),
    path('productDetail/<int:id>',views.productDetail,name="productDetail"),
    path('search',views.search,name="search"),
    path('search/<str:heading>',views.search,name="search"),
    path('cart/',views.cart,name="cart"),
    path('checkout/',views.checkout,name="checkout"),
    path('logout/<str:username>',views.logout,name="account_logout"),
    path("reset_password_done",views.reset_password_done,name="reset_password_done"),
    path('update_password/<str:username>',views.change_password,name="update_password"),
    path("cust_logout",views.cust_logout,name="cust_logout"),
    path("Seller_center",Seller_views.seller_center,name="seller_center"),
    path("SellerDetail/",Seller_views.seller_detail,name="SellerDetail"),
    path("seller_logout",Seller_views.seller_logout,name="seller_logout"),
    path("add_product",Seller_views.add_product,name="add_product"),
    path('SellerDetail',Seller_views.seller_detail,name="SellerDetail"),
    path("seller_logout",Seller_views.seller_logout,name="seller_logout"),
    path('SellerDetailUpdate',Seller_views.seller_detail_update,name="SellerDetailUpdate"),
    path("edit_product/<str:pk>/",Seller_views.edit_product,name="edit_product"),
    path("delete_product/<str:pk>/",Seller_views.delete_product,name="delete_product"),
    path("delete_cart/<int:id>",views.delete_cart,name="delete_cart"),
    path("addComment/<int:id>", views.addComment,name="addComment"),
    path('reports/',Seller_views.reports,name="reports"),
    path('about/',views.about,name="about")
]

E_Mart/order/urls.py
from django.urls import path
from . import views
app_name="order"
urlpatterns=[
            path('myorders/',views.my_orders,name="my_orders"),
            path('order_details/<int:id>/',views.order_details,name="order_details"),
            path('order_delivered/<int:id>/',views.order_delivered,name="order_delivered"),
            path("orders/",views.seller_orders,name="seller_orders"),
            path('seller_order_details/<int:id>/',views.seller_orders_details,name="seller_orders_details"),
            path('seller_confirmation/<int:id>/',views.seller_confirmation,name="seller_confirmation")
]

E_Mart/Home_Module/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm
from Home_Module.models import ProductReview, Products
class AddProductForm(ModelForm):
    productName=forms.CharField(label="Product Name",
        widget=forms.TextInput(
            attrs={"placeholder":"Ex. Nikon Coolpix A300 Digital Camera","class":"input","autocomplete":"off"}
        )
    )
    brand=forms.CharField(label="Brand Name",
        widget=forms.TextInput(
            attrs={"placeholder":"Rolex","class":"input","autocomplete":"off"}
        )

    )
    description=forms.CharField(label="Description",required=True,
        widget=forms.Textarea(
            attrs={"autocomplete":"off","class":"input"}
        )

    )
    price=forms.CharField(label="Price",
        widget=forms.NumberInput(
            attrs={"class":"input","autocomplete":"off","min":"1"}
        )

    )
    quantity=forms.CharField(label="Quantity",
        widget=forms.NumberInput(
            attrs={"class":"input","autocomplete":"off","min":"1"}
        )

    )
    image1=forms.ImageField(
        label="Image1",required=False,
        widget=forms.FileInput(
            attrs={"class":"input","autocomplete":"off","accept":"image/*"}
        )
    )

    image2=forms.ImageField(
        label="Image2",required=False,
        widget=forms.FileInput(
            attrs={"class":"input","autocomplete":"off","accept":"image/*"}
        )
    )
    image3=forms.ImageField(
        label="Image3",required=False,
        widget=forms.FileInput(
            attrs={"class":"input","autocomplete":"off","accept":"image/*"}
        )
    )
    image4=forms.ImageField(
        label="Image4",required=False,
        widget=forms.FileInput(
            attrs={"class":"input","autocomplete":"off","accept":"image/*"}
        )
    )
 
    class Meta:
        model=Products
        exclude = ['sellerId']





    # #username=current_password=forms.HiddenInput(max_length=100,required=True,widget=forms.CharField(attrs={'hidden'}))
    # productName=forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={"placeholder":"Ex Red T-Shirt"}))
    # category=forms.CharField(max_length=100,required=True,widget=forms.Select(choices=category_choice))
    # #cnfrm_passwd=forms.CharField(max_length=100,required=True,widget=forms.PasswordInput(attrs={'placeholder':"confirm new password",'id':'cnfrm_passwd'}))
class ProductReviewForm(ModelForm):
    class Meta:
        model = ProductReview
        fields = ['subject', 'content', 'rate']

E_Mart/Home_Module/views.py
from datetime import date
from django.views import View
from django.db.models import Q
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,HttpResponseNotFound
from rest_framework.parsers import JSONParser
from django.views.decorators.csrf import csrf_exempt
from django.http.response import JsonResponse
from django import forms
from django.urls import reverse
from django.contrib import auth,messages
from django.conf import settings
from django.contrib.auth import update_session_auth_hash
from Home_Module.models import ProductReview, User,SellerDetail,Products,Cart,SellerDetail,ProductReviewForm
from order.models import Order,OrderDetails
from shipping.models import ShippingDetail
from .email_handler import token_generator,send_link
from django.utils.encoding import force_bytes,force_text,DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from .Serializer import CustomerSerializer
from .utility_functions import isUserLogin,permission_check,cart_lenght
import json
# Create your views here.

@csrf_exempt
def cust_api(request,name='',email=''):
    if request.method=="GET":
        if len(name)!=0 or len(email)!=0:
            try:
                if len(email)==0:
                    cust=User.objects.get(username=name)
                else:
                    cust=User.objects.get(email=email)
                cust_serializer=CustomerSerializer(cust)
                return JsonResponse(cust_serializer.data,safe=False)      
                
            except User.DoesNotExist:
                return JsonResponse(None,safe=False)

                              
        customers=User.objects.all()
        cust_serializer=CustomerSerializer(customers,many=True)
        return JsonResponse(cust_serializer.data,safe=False)
    
def login(request):
    if request.method=="GET":
        if "username" in request.session:
            return render(request,"Home_Module/signup.html",context={"username":request.session['username'],"password":request.session['password']})
        return render(request,"Home_Module/signup.html")
    if request.method=="POST":
        #Filtering Latest Objects on The basis of ID
        prod=Products.objects.all().order_by('-id')
        prod=prod[:4]
    
        #Filtering Featured Products
        #select_related basically works as join
        feature=ProductReview.objects.select_related('products').all().order_by('-rate')
        if len(feature)>4:
            feature=feature[:4]
        username= request.POST['username']
        password= request.POST['password']  
        cust = auth.authenticate(username=username,password=password)
   
        if cust is None:
            errorMessage="Invalid Username or Password"
        elif  not cust.is_active:
            errorMessage="Your account is not active.please check your email address"
        else: 
            
            if 'is_seller' in request.POST: #checking if the request has come from seller center or not
                if not cust.is_seller:# if request has come from seller center ,checking if user is registered as seller
                    errorMessage="you are not registered as seller"
                else:
                    if request.POST.get("remember"):
                        request.session['usernameSeller']=username
                        request.session['passwordSeller']=password
                    request.session['seller']=cust.username

                    try:                     
                        user=SellerDetail.objects.get(user=cust)
                        return HttpResponseRedirect(reverse("Home_Module:seller_center"))
                    except SellerDetail.DoesNotExist:
                        return HttpResponseRedirect(reverse("Home_Module:SellerDetail"))
            else:
                if cust.is_seller:
                    errorMessage="you are not registered as a Customer"
                else:
                    if request.POST.get("remember"):
                        request.session['username']=username
                        request.session['password']=password
                    request.session['user']=cust.username
                    cart=Cart.objects.filter(user=cust)#cart Notification
                    #context setting
                    context={"user":cust,"notify":len(cart),"Products":prod,"feature":feature}
                    return render(request,"Home_Module/Home.html",context=context)
        if "is_seller" in request.POST:
            return render(request,"Seller_Module/SellerSignUp.html",context={"errorMessage":errorMessage})
        else:
            return render(request,"Home_Module/SignUp.html",context={"errorMessage":errorMessage})
    
def home(request):
    #Filtering Latest Objects on The basis of ID
    prod=Products.objects.all().order_by('-id')
    prod=prod[:4]
    
    #Filtering Featured Products
    #select_related basically works as join
    feature=ProductReview.objects.select_related('products').all().order_by('-rate')
    if len(feature)>4:
        feature=feature[:4]
    
    user=isUserLogin(request,'user')
    if user is not None:
        cart=Cart.objects.filter(user=user)
        context={"user":user,"notify":len(cart),"Products":prod,"feature":feature}
        return render(request,"Home_Module/Home.html",context=context)
    context={"Products":prod,"feature":feature}
    return render(request,"Home_Module/Home.html",context=context)

def forget(request):
    if request.method!="POST":
        return render(request,"Home_Module/ForgetPass.html")
    else:
        email=request.POST['email']
        if len(email)==0:
            messages.error(request,"Please enter your email")   
        else:     
            try:
                user=User.objects.get(email=email,is_staff=False)
                if not user.is_active:
                    messages.warning(request,"your account is not active .please check your inbox")
                else:
                    email_subject="Reset Password"
                    email_body=f'Hey {user.username}\n You have requested a password reset.Please click the following link to  reset your password\n'
                    send_link(email_subject,email_body,user,'reset_password')
                    messages.info(request,f'Please check your inbox.we have sent an email at {user.email} for password reset')
            except User.DoesNotExist:
                messages.error(request,"No such user exist")
        return HttpResponseRedirect(reverse("Home_Module:forget"))
            
def contact(request):
    return render(request,"Home_Module/contact.html")

def search(request,heading=''):
    query=None
    if len(heading)!=0:
        query=heading
    else:
        query=request.GET['query']
    #filtering Products
    if query:
        context={"products":Products.objects.filter(productName__icontains=query)or 
        Products.objects.filter(brand__icontains=query)or Products.objects.filter(category__icontains=query)or Products.objects.filter(description__icontains=query) }
    else:
        context={}
    user=permission_check(request)
    if user is not None:
        context['user']=user
        context['notify']=cart_lenght(user)
    return render(request,"Home_Module/products.html",context=context)
    
def productDetail(request,id):
    product=Products.objects.get(pk=id)
    comments=ProductReview.objects.all().filter(products=product)
    user=permission_check(request) 
    try:
        p=ProductReview.objects.get(users=user,products=id)  
    except ProductReview.DoesNotExist:
         p = None
         print("pathan")
    if request.method=="GET":
        category=product.category
        name=product.productName
        relatedProd=Products.objects.filter(productName__icontains=name)and Products.objects.filter(category=category)
        if (len(relatedProd) >=4):
            relatedProd=relatedProd[:4]
        else:
            relatedProd=relatedProd
        context={}
        if user is not None:
            cart=Cart.objects.filter(user=user)
            context={"product":product,"comment":comments,"p":p,"user":user,"rProd":relatedProd,"notify":len(cart)}
            print("shoaib")
            return render(request,"Home_Module/productDetail.html",context=context)
           
        context={"product":product,"p":p,"comment":comments,"user":user,"rProd":relatedProd}
        return render(request,"Home_Module/productDetail.html",context=context)
    if request.method=="POST":   
        if not user in User.objects.all():
            messages.error(request,"You have to login first")
            return HttpResponseRedirect(reverse("Home_Module:signup"))
        cart=None
        try:
            cart=Cart.objects.get(user=user,product=product)
            cart.qty=cart.qty+int(request.POST['qty'])
        except Cart.DoesNotExist:
            cart=Cart.objects.create(user=user,product=product)
            cart.qty=request.POST['qty']
        cart.save()
        return HttpResponseRedirect(reverse("Home_Module:cart"))
def signup(request):
    if request.method=='GET':
        return HttpResponseRedirect(reverse("Home_Module:login"))
    
    elif request.method=='POST':
        email=request.POST['email']
        username=request.POST['username']
        password=request.POST['password'] 
        user = User.objects.create_user(username=username, email=email)
        user.set_password(password)
        user.is_active = False
        user.is_social_user=False
        if 'is_seller' in request.POST:
            user.is_seller=True
        user.save()
        email_subject="Activate your account"
        email_body=f'Hey {user.username}\n Thanks for regestring on E_Mart.We are very delighted to have you.Please click the following link to activate your account\n'
        send_link(email_subject,email_body,user,'activate')

E_Mart/Home_Module/templates/Seller_Module/AllProduct.html
{%extends 'Seller_Module/Seller_base.html'%}
{%load static %}

{%block css%}
<link rel="stylesheet" href="{%static '/css/seller/AllProduct.css'%}"/>
{%endblock%}
{%block body%}
<h1 class="heading">Your Products</h1>
<div style="overflow-x:auto;">
    <table>
        <thead>
            <tr>
                <th>No.</th>
                <th>Name</th>
                <th>Category</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Image</th>
                <th></th>
            </tr>
        </thead>
        <tbody class="tableBody">
           {% for i in products %}
            <tr>
                <td>  {{i.productName}} </td>
                <td>   {{i.category}} </td>
                <td>   {{i.quantity}}  </td>
                <td>   {{i.price}}  </td>
                <td><img class="small-img" src="{{i.image1.url}}">  </td>
                <td>
                <a href="{%url 'Home_Module:edit_product' i.pk %}" class="btn button2" role="button">Edit</a>
                <a href="{%url 'Home_Module:delete_product' i.pk %}" class="btn button3" role="button">Remove</a>
                </td>
             </tr>
            {% endfor %}          
        </tbody>
    </table>
</div>
{%endblock%}

E_Mart/Home_Module/templates/Seller_Module/SellerDetailUpdate.html
{%load static %}
<html>
<head>
    <title>Details</title>
    <link rel="stylesheet" href="{%static '/css/seller/SellerDetail.css'%}">
    <script  src="{%static  'javascript/seller/SellerDetailUpdate.js' %}"></script>
    
</head>
<body>
<div class="container">  
<h2>Update Detail</h2>
        <form method="POST" action="{%url 'Home_Module:SellerDetailUpdate'%}" onsubmit="return detailUpdateValidation()">
          {%csrf_token%}
         <div class="txt_field">
            <input  type="text" id="shopName" value="{{detail.shop}}" onkeyup="allnumeric(id,'shopEror')" name="shop" placeholder="Shope Name"/>
             <span id="shopEror" class="error_style"></span>
          </div> 
        <div class="txt_field">
            <input   type="text" id="PhoneNo" value="{{detail.phone}}" onkeyup="allnumeric(id,'phoneEror')" name="phone" placeholder="Phone No i.e 03001122333"/>
            <span id="phoneEror" class="error_style"></span>
          </div> 
        <div class="txt_field">
            <input    type="text" id="cnic" value="{{detail.cnic}}" onkeyup="allnumeric(id,'cnicEror')" name="cnic" placeholder="CNIC i.e 3110170901355"/>
           <span id="cnicEror" class="error_style"></span>
          </div>
        <div class="txt_field">
            <input   type="text" id="address" value="{{detail.address}}" onkeyup="allnumeric(id,'AddressEror')" name="address" placeholder="Address"/>
            <span id="AddressEror" class="error_style"></span>
          </div>
        <div class="txt_field">
            <input  type="text" id="account" value="{{detail.account_no}}" onkeyup="allnumeric(id,'AccountEror')" name="account" placeholder="Bank Account No."/>
            <span id="AccountEror" class="error_style"></span>
          </div> 
            
            <button type="submit" id="subbtn"  class="submit-btn">Update</button>
                
            </form>
              
        </div>
       
    </body>
</html>

E_Mart/Home_Module/templates/Seller_Module/SellerSignUp.html
{%load static%}
<html>
<head>
    <title>Seller Center</title>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@1,700&family=Montserrat&family=Raleway&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Amatic+SC&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Amatic+SC&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{%static '/css/seller/SellerSignUp.css'%}">
        <link rel="stylesheet" href="{%static '/css/home/messages.css'%}"/>
</head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-2">
                  <div class="abc">
                    <div class="visibility">
                        {% for message in messages %}
                        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                            {{ message }}
                        </div>
                        {% endfor %}
                        <h1 class="emart">EMART</h1>
                        <h3>Step In to</h3><h1> Seller Center!</h1>
                        <h2>Three Easy steps to Start Selling</h2>
                        <div class="content">
                            <br>
                            <!--img src="log.png" height="30px" width="30px"-->
                            <h3>1 Sign Up to Store Profile</h3>
                        <h3>2 Upload your Products to Start Selling</h3>
                        <h3>3 Adopt Tools to Maximize Sales</h3>
                    </div>
                    <div class="repu">
                        <br>
                        <p >EMART is one of the best Selling Website
                            <br>
                            Where You Can Sell Each of Your Product with ease
                            <br>
                            Once you get start with,Your Online Shop is ready
                        </p>
                      </div> 
                    </div>
                </div>
                <a href="{%url 'Home_Module:home'%}" class= "Backbtn">&#x2190;Go Back </a>
            </div>
        <div class="col-2">      
        <div class="card">
        <div class="inner-box" id="card">
        <div class="card-front">
            <img src="back.jpg" class="img-back">
            <h2>LOGIN</h2>
            <form method="POST" action="{%url 'Home_Module:login'%}" onsubmit="return loginSubmit()">
                {% csrf_token %}
                <div>
                <input type="hidden" name="is_seller" value="seller">
               <input  name="username" autofocus id="loginUsername" value="{{username}}"   type="text" class="input-box" placeholder="Username" />
                <span id="nameError" class="error_style"></span>
                </div>
                <div>

                <input  name="password"  id="loginPasswd" value="{{password}}"  type="password" class="input-box" placeholder="Password" />
                <span id="pswdError" class="error_style">{{errorMessage}}</span>
                </div>
                <input type="checkbox" name="remember" class="input-check"><span class="input-span">Remember me</span>
                <button id="login_btn"   class="submit_btn" >Login</button>
                
            </form>
           <p class="forget"> <a href="{%url 'Home_Module:forget'%}">Forget password</a></p>
            <p class="message">Not Registered?<a href="#" onclick="openRegister()">Register</a></p>
       </div>
        <div class="card-back">
            <img src="{%static '/Images/login.jpg'%}" class="img-back">
            <h2>REGISTER</h2>
            <form method="POST" action="{%url 'Home_Module:signup'%}">
                {% csrf_token %}
                <input type="hidden" name="is_seller" value="seller">
                <div>
                <input  name="username" autofocus id="username"  onkeyup="handleChangeRegister(id)" onfocus="handleFocus(id)"  type="text" class="input-box" placeholder="Username" />
                <span id="usernameError" class="error_style"></span>
                </div>
                 <div>
                <input  name="email" id="email" onkeyup="handleChangeRegister(id)" onfocus="handleFocus(id)"   type="email" class="input-box" placeholder="Email" />
                <span id="emailError" class="error_style"></span>
                </div>
                 <div>
                <input  name="password" id="password" onkeyup="handleChangeRegister(id)" onfocus="handleFocus(id)"   type="password" class="input-box" placeholder="Password" />
                <span id="passwordError" class="error_style"></span>
                </div>
                 <div>
                <input  name="cnfrmPassword" id="cnfrmPassword" onkeyup="handleChangeRegister(id)" onfocus="handleFocus(id)" id="SellercnfrmPswd"   type="password" class="input-box" placeholder="Confirm password" />
                <span id="cnfrmPasswordError" class="error_style"></span>
                </div>
                <input id="chkbox" type="checkbox" onchange="handleChangeRegister(id)" class="check_box"/><span class="checkbox_style" id="registerSpan">I agree all terms&policy of E-MART.</span>
                <button id="regbtn" disabled type="submit" class="submit-btn">Register</button>
                
            </form>
            
<!--            <button type="button" class="btn" onclick="openLogin()">I've an account</button>-->
            <p class="message">Registered?<a href="#" onclick="openLogin()">Login</a></p>
       </div>
                    
        </div>
            
        </div>
    </div>
        </div>
    </div>
        <script  src="{%static  'javascript/seller/Seller.js' %}"></script>
        <script  src="{%static  'javascript/home/SignUp.js' %}"></script>
        
        
    </body>
</html>

E_Mart/Home_Module/templates/Seller_Module/Seller_base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Seller Center</title>
	<link rel="stylesheet" href="{%static '/css/seller/home_Seller.css'%}">
  {%block css%}
  {%endblock%}
  
  <link rel="stylesheet" href="{%static '/css/home/messages.css'%}"/>
 
  <meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script>
		$(document).ready(function(){
			$(".hamburger").click(function(){
			   $(".wrapper").toggleClass("collapse");
			});
		});
	</script>
</head>
<body>

<div class="wrapper">
  <div class="top_navbar">
    <div class="hamburger">
       <div class="one"></div>
       <div class="two"></div>
       <div class="three"></div>
    </div>
    <div class="top_menu">
      <div class="logo">EMart</div>
      <ul>
        <li><a href="#">
          <span class="fas fa-search"></span></a>
        </li>
        <li><a href="#">
          <i class="fas fa-bell"></i>
          </a></li>
        <li>{{user.username}}</li>
      </ul>
    </div>
  </div>
  <div class="sidebar">
    <ul>
      <li><a href="{%url 'Home_Module:seller_center' %}"><i class="fa fa-home" aria-hidden="true"></i>Home</a></li>
      <li class="dropdown"><a href=""><i class="fa fa-cog" aria-hidden="true"></i>Products<span>&rsaquo;</span></a>
        <ul>
            <li><a href="{%url 'Home_Module:add_product' %}"><i class="fa fa-user-circle-o" aria-hidden="true"></i>Add product</a></li>
            
            
          </ul>
        
        </li>
      <li><a href="{%url 'order:seller_orders'%}">Order & Reviews</a></li>
      <li><a href="{%url 'Home_Module:reports'%}">Reports</a></li>
      <li class="dropdown"><a href=""><i class="fa fa-cog" aria-hidden="true"></i>Settings<span>&rsaquo;</span></a>
      <ul>
          <li ><a href="{%url 'Home_Module:SellerDetailUpdate' %}"><i class="fa fa-user-circle-o" aria-hidden="true"></i>Profile</a></li>
          <li><a href="{%url 'Home_Module:update_password' user.username%}"><i class="fa fa-pencil" aria-hidden="true"></i>Update Password</a></li>
        </ul>
      
      </li>
      <li><a href="{%url 'Home_Module:account_logout' user.username %}"><i class="fa fa-lock" aria-hidden="true"></i>Logout</a></li>   
    </ul>
  </div>
  
  <div class="main_container">
    {% for message in messages %}
    <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {{ message }}
    </div>
    {% endfor %}
    {%block body%}
    {%endblock%}
	<script  src="{%static  'javascript/seller/Seller.js' %}"></script>
  <script  src="{%static  'javascript/home/SignUp.js' %}"></script>
</body>
</html>
{%block js%}
{%endblock%}

E_Mart/Home_Module/templates/Seller_Module/UpdatePassword.html
{%extends 'Seller_Module/Seller_base.html'%}
{%load static%}
{%block css%}
<link rel="stylesheet" href="{%static '/css/seller/UpdatePassword.css'%}">
{%endblock%}
{%block body%}
<div class="color">
    <div class="center">
        <h1 class="heading">Update PASSWORD<h1>
        <form method="POST" action="{%url 'Home_Module:update_password' user.username%}">
            {%csrf_token%}
            <div>
                <input type="password" name="password" id="password" onkeyup="handleResetChange(id)" onfocus="handleFocus(id)"  class="txt_field" placeholder="Old Password" />
                 <span id="passwordError" class="error_style"></span>
             </div> 
            <div>
                <input type="password" name="newPasswd" id="newPassword" onkeyup="handleResetChange(id)" onfocus="handleFocus(id)" class="txt_field" placeholder="Enter New Password">
                <span id="newPasswordError" class="error_style"></span>
            </div>
            <div>
               <input type="password" name="cnfrmPassword" id="cnfrmPassword" onkeyup="handleResetChange(id)" onfocus="handleFocus(id)"  class="txt_field" placeholder="Confirm new Password" />
                <span id="cnfrmPasswordError" class="error_style"></span>
            </div> 
             <button id="resetbtn" disabled type="submit" class="submit_btn">Update Password</button>
        </form>
    </div>
</div>
{%endblock%}
        

E_Mart/Home_Module/templates/Seller_Module/addproduct.html
{%extends 'Seller_Module/Seller_base.html'%}
{%load static %}
{%block css%}
<link rel="stylesheet" href="{%static '/css/seller/product.css'%}"/>
{%endblock%}
{%block body%}
<h1>{{heading}}</h1>
<form method="POST" {%if pk%} action="{%url 'Home_Module:edit_product' pk%}" {%else%} action="{%url 'Home_Module:add_product'%}" {%endif%} enctype='multipart/form-data'>
    
    {%csrf_token%}
    <label >Product Name:</label>
    {{ form.productName }}
    <label >Brand Name:</label>
    {{ form.brand }}
    <label >Price:</label>
    {{form.price}}
    <label >Qunatity:</label>
    {{ form.quantity }}
    <label >Image1:</label>
    {%if form.instance.image1.url is not None%}
        <span class="margins">currently:
        <a href="{{form.instance.image1.url}}">{{form.instance.image1.url}}</a>
        </span>
    {%endif%}
   {{form.image1}}
   <label >Image2:</label>
   {%if form.instance.image2.url is not None%}
   <span class="margins">currently:
   <a href="{{form.instance.image2.url}}">{{form.instance.image2.url}}</a>
   </span>
    {%endif%}
    {{form.image2}}
    <label >Image3:</label>
    {%if form.instance.image3.url is not None%}
    <span class="margins">currently:
    <a href="{{form.instance.image3.url}}">{{form.instance.image3.url}}</a>
    </span>
     {%endif%}
     {{form.image3}}
     <label >Image4:</label>
     {%if form.instance.image4.url is not None%}
     <span class="margins">currently:
     <a href="{{form.instance.image4.url}}">{{form.instance.image4.url}}</a>
     </span>
      {%endif%}
      {{form.image4}}
    <label >category</label>
    {{form.category}}
    <label >Description:</label>
    {{form.description}}




    <button class="add">{{button}}</button>
</form>
{%endblock%}