E_Mart/E_Mart/urls.py
from django.contrib import admin
from django.urls import path,include
from Home_Module import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home_Module.urls')),
    path('shipping/',include('shipping.urls')),
    path('order/',include('order.urls')),
    path('accounts/',include('allauth.urls')),	
    path('activate/<uidb64>/<token>',views.Verification.as_view(),name="activate"),
    path('reset_password/<uidb64>/<token>',views.reset_password,name="reset_password"),
    
   
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

E_Mart/Home_Module/urls.py
from django.urls import path
from .import views,Seller_views
from django.contrib.auth import views as auth_views
app_name='Home_Module'
urlpatterns=[
    path('',views.home,name="home"),
    path('login/', views.login,name="login"),
    path('signup/',views.signup,name="signup"),
    path('forget',views.forget,name="forget"),
    path('customer/',views.cust_api,name="cust_api"),
    path('customer/username=<str:name>',views.cust_api,name="cust_api"),
    path('customer/email=<str:email>',views.cust_api,name="cust_api"),
    path('contact',views.contact,name="contact"),
    path('productDetail/<int:id>',views.productDetail,name="productDetail"),
    path('search',views.search,name="search"),
    path('search/<str:heading>',views.search,name="search"),
    path('cart/',views.cart,name="cart"),
    path('checkout/',views.checkout,name="checkout"),
    path('logout/<str:username>',views.logout,name="account_logout"),
    path("reset_password_done",views.reset_password_done,name="reset_password_done"),
    path('update_password/<str:username>',views.change_password,name="update_password"),
    path("cust_logout",views.cust_logout,name="cust_logout"),
    path("Seller_center",Seller_views.seller_center,name="seller_center"),
    path("SellerDetail/",Seller_views.seller_detail,name="SellerDetail"),
    path("seller_logout",Seller_views.seller_logout,name="seller_logout"),
    path("add_product",Seller_views.add_product,name="add_product"),
    path('SellerDetail',Seller_views.seller_detail,name="SellerDetail"),
    path("seller_logout",Seller_views.seller_logout,name="seller_logout"),
    path('SellerDetailUpdate',Seller_views.seller_detail_update,name="SellerDetailUpdate"),
    path("edit_product/<str:pk>/",Seller_views.edit_product,name="edit_product"),
    path("delete_product/<str:pk>/",Seller_views.delete_product,name="delete_product"),
    path("delete_cart/<int:id>",views.delete_cart,name="delete_cart"),
    path("addComment/<int:id>", views.addComment,name="addComment"),
    path('reports/',Seller_views.reports,name="reports"),
    path('about/',views.about,name="about")
]

E_Mart/order/urls.py
from django.urls import path
from . import views
app_name="order"
urlpatterns=[
            path('myorders/',views.my_orders,name="my_orders"),
            path('order_details/<int:id>/',views.order_details,name="order_details"),
            path('order_delivered/<int:id>/',views.order_delivered,name="order_delivered"),
            path("orders/",views.seller_orders,name="seller_orders"),
            path('seller_order_details/<int:id>/',views.seller_orders_details,name="seller_orders_details"),
            path('seller_confirmation/<int:id>/',views.seller_confirmation,name="seller_confirmation")
]

E_Mart/Home_Module/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm
from Home_Module.models import ProductReview, Products
class AddProductForm(ModelForm):
    productName=forms.CharField(label="Product Name",
        widget=forms.TextInput(
            attrs={"placeholder":"Ex. Nikon Coolpix A300 Digital Camera","class":"input","autocomplete":"off"}
        )
    )
    brand=forms.CharField(label="Brand Name",
        widget=forms.TextInput(
            attrs={"placeholder":"Rolex","class":"input","autocomplete":"off"}
        )

    )
    description=forms.CharField(label="Description",required=True,
        widget=forms.Textarea(
            attrs={"autocomplete":"off","class":"input"}
        )

    )
    price=forms.CharField(label="Price",
        widget=forms.NumberInput(
            attrs={"class":"input","autocomplete":"off","min":"1"}
        )

    )
    quantity=forms.CharField(label="Quantity",
        widget=forms.NumberInput(
            attrs={"class":"input","autocomplete":"off","min":"1"}
        )

    )
    image1=forms.ImageField(
        label="Image1",required=False,
        widget=forms.FileInput(
            attrs={"class":"input","autocomplete":"off","accept":"image/*"}
        )
    )

    image2=forms.ImageField(
        label="Image2",required=False,
        widget=forms.FileInput(
            attrs={"class":"input","autocomplete":"off","accept":"image/*"}
        )
    )
    image3=forms.ImageField(
        label="Image3",required=False,
        widget=forms.FileInput(
            attrs={"class":"input","autocomplete":"off","accept":"image/*"}
        )
    )
    image4=forms.ImageField(
        label="Image4",required=False,
        widget=forms.FileInput(
            attrs={"class":"input","autocomplete":"off","accept":"image/*"}
        )
    )
 
    class Meta:
        model=Products
        exclude = ['sellerId']





    # #username=current_password=forms.HiddenInput(max_length=100,required=True,widget=forms.CharField(attrs={'hidden'}))
    # productName=forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={"placeholder":"Ex Red T-Shirt"}))
    # category=forms.CharField(max_length=100,required=True,widget=forms.Select(choices=category_choice))
    # #cnfrm_passwd=forms.CharField(max_length=100,required=True,widget=forms.PasswordInput(attrs={'placeholder':"confirm new password",'id':'cnfrm_passwd'}))
class ProductReviewForm(ModelForm):
    class Meta:
        model = ProductReview
        fields = ['subject', 'content', 'rate']

E_Mart/Home_Module/views.py
from datetime import date
from django.views import View
from django.db.models import Q
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,HttpResponseNotFound
from rest_framework.parsers import JSONParser
from django.views.decorators.csrf import csrf_exempt
from django.http.response import JsonResponse
from django import forms
from django.urls import reverse
from django.contrib import auth,messages
from django.conf import settings
from django.contrib.auth import update_session_auth_hash
from Home_Module.models import ProductReview, User,SellerDetail,Products,Cart,SellerDetail,ProductReviewForm
from order.models import Order,OrderDetails
from shipping.models import ShippingDetail
from .email_handler import token_generator,send_link
from django.utils.encoding import force_bytes,force_text,DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from .Serializer import CustomerSerializer
from .utility_functions import isUserLogin,permission_check,cart_lenght
import json
# Create your views here.

@csrf_exempt
def cust_api(request,name='',email=''):
    if request.method=="GET":
        if len(name)!=0 or len(email)!=0:
            try:
                if len(email)==0:
                    cust=User.objects.get(username=name)
                else:
                    cust=User.objects.get(email=email)
                cust_serializer=CustomerSerializer(cust)
                return JsonResponse(cust_serializer.data,safe=False)      
                
            except User.DoesNotExist:
                return JsonResponse(None,safe=False)

                              
        customers=User.objects.all()
        cust_serializer=CustomerSerializer(customers,many=True)
        return JsonResponse(cust_serializer.data,safe=False)
    
def login(request):
    if request.method=="GET":
        if "username" in request.session:
            return render(request,"Home_Module/signup.html",context={"username":request.session['username'],"password":request.session['password']})
        return render(request,"Home_Module/signup.html")
    if request.method=="POST":
        #Filtering Latest Objects on The basis of ID
        prod=Products.objects.all().order_by('-id')
        prod=prod[:4]
    
        #Filtering Featured Products
        #select_related basically works as join
        feature=ProductReview.objects.select_related('products').all().order_by('-rate')
        if len(feature)>4:
            feature=feature[:4]
        username= request.POST['username']
        password= request.POST['password']  
        cust = auth.authenticate(username=username,password=password)
   
        if cust is None:
            errorMessage="Invalid Username or Password"
        elif  not cust.is_active:
            errorMessage="Your account is not active.please check your email address"
        else: 
            
            if 'is_seller' in request.POST: #checking if the request has come from seller center or not
                if not cust.is_seller:# if request has come from seller center ,checking if user is registered as seller
                    errorMessage="you are not registered as seller"
                else:
                    if request.POST.get("remember"):
                        request.session['usernameSeller']=username
                        request.session['passwordSeller']=password
                    request.session['seller']=cust.username

                    try:                     
                        user=SellerDetail.objects.get(user=cust)
                        return HttpResponseRedirect(reverse("Home_Module:seller_center"))
                    except SellerDetail.DoesNotExist:
                        return HttpResponseRedirect(reverse("Home_Module:SellerDetail"))
            else:
                if cust.is_seller:
                    errorMessage="you are not registered as a Customer"
                else:
                    if request.POST.get("remember"):
                        request.session['username']=username
                        request.session['password']=password
                    request.session['user']=cust.username
                    cart=Cart.objects.filter(user=cust)#cart Notification
                    #context setting
                    context={"user":cust,"notify":len(cart),"Products":prod,"feature":feature}
                    return render(request,"Home_Module/Home.html",context=context)
        if "is_seller" in request.POST:
            return render(request,"Seller_Module/SellerSignUp.html",context={"errorMessage":errorMessage})
        else:
            return render(request,"Home_Module/SignUp.html",context={"errorMessage":errorMessage})
    
def home(request):
    #Filtering Latest Objects on The basis of ID
    prod=Products.objects.all().order_by('-id')
    prod=prod[:4]
    
    #Filtering Featured Products
    #select_related basically works as join
    feature=ProductReview.objects.select_related('products').all().order_by('-rate')
    if len(feature)>4:
        feature=feature[:4]
    
    user=isUserLogin(request,'user')
    if user is not None:
        cart=Cart.objects.filter(user=user)
        context={"user":user,"notify":len(cart),"Products":prod,"feature":feature}
        return render(request,"Home_Module/Home.html",context=context)
    context={"Products":prod,"feature":feature}
    return render(request,"Home_Module/Home.html",context=context)

def forget(request):
    if request.method!="POST":
        return render(request,"Home_Module/ForgetPass.html")
    else:
        email=request.POST['email']
        if len(email)==0:
            messages.error(request,"Please enter your email")   
        else:     
            try:
                user=User.objects.get(email=email,is_staff=False)
                if not user.is_active:
                    messages.warning(request,"your account is not active .please check your inbox")
                else:
                    email_subject="Reset Password"
                    email_body=f'Hey {user.username}\n You have requested a password reset.Please click the following link to  reset your password\n'
                    send_link(email_subject,email_body,user,'reset_password')
                    messages.info(request,f'Please check your inbox.we have sent an email at {user.email} for password reset')
            except User.DoesNotExist:
                messages.error(request,"No such user exist")
        return HttpResponseRedirect(reverse("Home_Module:forget"))
            
def contact(request):
    return render(request,"Home_Module/contact.html")

def search(request,heading=''):
    query=None
    if len(heading)!=0:
        query=heading
    else:
        query=request.GET['query']
    #filtering Products
    if query:
        context={"products":Products.objects.filter(productName__icontains=query)or 
        Products.objects.filter(brand__icontains=query)or Products.objects.filter(category__icontains=query)or Products.objects.filter(description__icontains=query) }
    else:
        context={}
    user=permission_check(request)
    if user is not None:
        context['user']=user
        context['notify']=cart_lenght(user)
    return render(request,"Home_Module/products.html",context=context)
    
def productDetail(request,id):
    product=Products.objects.get(pk=id)
    comments=ProductReview.objects.all().filter(products=product)
    user=permission_check(request) 
    try:
        p=ProductReview.objects.get(users=user,products=id)  
    except ProductReview.DoesNotExist:
         p = None
         print("pathan")
    if request.method=="GET":
        category=product.category
        name=product.productName
        relatedProd=Products.objects.filter(productName__icontains=name)and Products.objects.filter(category=category)
        if (len(relatedProd) >=4):
            relatedProd=relatedProd[:4]
        else:
            relatedProd=relatedProd
        context={}
        if user is not None:
            cart=Cart.objects.filter(user=user)
            context={"product":product,"comment":comments,"p":p,"user":user,"rProd":relatedProd,"notify":len(cart)}
            print("shoaib")
            return render(request,"Home_Module/productDetail.html",context=context)
           
        context={"product":product,"p":p,"comment":comments,"user":user,"rProd":relatedProd}
        return render(request,"Home_Module/productDetail.html",context=context)
    if request.method=="POST":   
        if not user in User.objects.all():
            messages.error(request,"You have to login first")
            return HttpResponseRedirect(reverse("Home_Module:signup"))
        cart=None
        try:
            cart=Cart.objects.get(user=user,product=product)
            cart.qty=cart.qty+int(request.POST['qty'])
        except Cart.DoesNotExist:
            cart=Cart.objects.create(user=user,product=product)
            cart.qty=request.POST['qty']
        cart.save()
        return HttpResponseRedirect(reverse("Home_Module:cart"))
def signup(request):
    if request.method=='GET':
        return HttpResponseRedirect(reverse("Home_Module:login"))
    
    elif request.method=='POST':
        email=request.POST['email']
        username=request.POST['username']
        password=request.POST['password'] 
        user = User.objects.create_user(username=username, email=email)
        user.set_password(password)
        user.is_active = False
        user.is_social_user=False
        if 'is_seller' in request.POST:
            user.is_seller=True
        user.save()
        email_subject="Activate your account"
        email_body=f'Hey {user.username}\n Thanks for regestring on E_Mart.We are very delighted to have you.Please click the following link to activate your account\n'
        send_link(email_subject,email_body,user,'activate')

E_Mart/Home_Module/templates/Home_Module/Home.html
{%extends 'base.html'%}
{%load static%}

{%block body%}
    <div class="home">
    <div class="container">
        <div class="row">
            <div class="col-2">
                <h1>WELCOME TO EMART!!</h1>
                <p><strong>EMART</strong> is one of the best online-shopping website.<br>You can buy <strong>quality products</strong> within suitable prices.<br>Except Purchasing You can also sell their Products.<br>This site is best choice for <strong>Customers</strong> As Well As<br>for <strong>Traders.</strong></p>
                <a href="" class= "Visitbtn">Visit EMART &#8594;</a>
            </div>
            <div class="col-2">
                <img src="/Images/products/images/welcome.png"/>
            </div>
        </div>
    </div>
    </div>
<!-------------------------Categories-------------->
<h2 class="title">Categories</h2>
<div class="categories">
<div class="small-Cat-container">
    <div class="row">
        <div class="col-3">
            <a href="{%url 'Home_Module:search' 'men'%}">
                <img src="/Images/products/images/bilal.jpg"/>
            </a>
            <h4 name="query">MEN's Fashion</h4>
        </div>
        <div class="col-3">
            <a href="{%url 'Home_Module:search' 'Women'%}">
                <img src="/Images/products/images/women.jpg"/>
            </a>
            <h4 name="query">Women's Fashion</h4>
        </div>
        <div class="col-3">
            <a href="{%url 'Home_Module:search' 'WBJ'%}">
                <img src="/Images/products/images/bag2.jpeg"/>
            </a>
            <h4 name="query">Bags & Jewellery</h4>
        </div>
        <div class="col-3">
            <a href="{%url 'Home_Module:search' 'Electronics'%}">
                <img src="/Images/products/images/electronics.jpg"/>
            </a>
            <h4 name="query">Electronic Devices</h4>
        </div>
        <div class="col-3">
            <a href="{%url 'Home_Module:search' 'accessories'%}">
                <img src="/Images/products/images/headphone.jpg"/>
            </a>
            <h4 name="query">E-Accessories</h4>
        </div>
        
        <div class="col-3">
            <a href="{%url 'Home_Module:search' 'home'%}">
                <img src="/Images/products/images/home.jpg"/>
            </a>
            <h4 name="query">Home Applainces</h4>
        </div>
        <div class="col-3">
            <a href="{%url 'Home_Module:search' 'sports'%}">
                <img src="/Images/products/images/sports.png"/>
            </a>
            <h4 name="query">SPORTS </h4>
        </div>
    </div>
</div>

</div>
<!------------------------Featured Products------------>
<div class="small-container">
<h2 class="title">Featured Products</h2>
<div class="row">
    {%for fProd in feature%}
    <div class="col-4">
        <a href="{%url 'Home_Module:productDetail' fProd.products.id%}">
            <img src="{{fProd.products.image1.url}}">
        </a>
        <h4 class="productsH4">{{fProd.products.productName}}</h4>
        <div class="rating">
            <label class="fa fa-star {% if fprod.products.averagereview >= 1 %} true-color {%else%} false-color{% endif %}"></label>
            <label class="fa fa-star {% if fprod.products.averagereview >= 2 %} true-color {%else%} false-color{% endif %}"></label>
            <label class="fa fa-star {% if fprod.products.averagereview >= 3 %} true-color {%else%} false-color{% endif %}"></label>
            <label class="fa fa-star {% if fprod.products.averagereview >= 4 %} true-color {%else%} false-color{% endif %}"></label>
            <label class="fa fa-star {% if fprod.products.averagereview >= 5 %} true-color {%else%} false-color{% endif %}"></label>
        </div>
        <p>{{fProd.products.price}}</p>
    </div>
    {%endfor%}
</div>
<h2 class="title">Latest Products</h2>
<div class="row">
    {%for prod in Products%}
    <div class="col-4">
        <a href="{%url 'Home_Module:productDetail' prod.id%}">
        <img src="{{prod.image1.url}}"/>
        </a>
        <h4 class="productsH4">{{prod.productName}}</h4>
        <div class="rating">
            <label class="fa fa-star {% if prod.averagereview >= 1 %} true-color {%else%} false-color{% endif %}"></label>
            <label class="fa fa-star {% if prod.averagereview >= 2 %} true-color {%else%} false-color{% endif %}"></label>
            <label class="fa fa-star {% if prod.averagereview >= 3 %} true-color {%else%} false-color{% endif %}"></label>
            <label class="fa fa-star {% if prod.averagereview >= 4 %} true-color {%else%} false-color{% endif %}"></label>
            <label class="fa fa-star {% if prod.averagereview >= 5 %} true-color {%else%} false-color{% endif %}"></label>
        </div>
        <p>{{prod.price}} <strong style="color:blue"> PKR</strong></p>
    </div>
    {% endfor%}
</div>
</div>

<!----------------------Offers Section---------------------------->
<div class="offer">
<div class="small-container">
    <div class="row">
        <div class="col-2">
            <img class="offer-img" src="/Images/products/images/exclusive.png"/>
        </div>
        <div class="col-2">
            <p>Exclusively Available Product on EMART.</p>
            <h1>Smart Brand</h1>
            <small>In marketing, a product is an object or system made available for consumer use;
             it is anything that can be offered to a market to satisfy the desire or need of a customer.
             In retailing, products are often referred to as merchandise, and in manufacturing, products 
             are bought as raw materials and then sold as finished goods.
             </small>
             <a href="" class="Visitbtn">Buy Now &#8594;</a>
        </div>
    </div>
</div>
</div>

{%endblock%}

    
              
  


<!--<html>
    <head>
        <title>Login Page</title>
    </head>
    <body>
        <h1>Home Page</h1>
        <a href="{%url 'Home_Module:signup'%}">Login</a>
        {%if LoginCust is not None%}
        {{LoginCust.username}}
        {%endif%}
        {%if user.is_authenticated%}
        {{user.first_name}}<br>
        {%endif%}
        
    </body>
</html>

E_Mart/Home_Module/templates/Home_Module/about.html
{%extends 'base.html'%}
{%block body%}
    <div class="container">
        <div class="about-div">
            <div class="about">
                <p><h2>We<i style="color:red" class="fa fa-heart" aria-hidden="true"></i>What we do</h2></p>
            </div>
        </di>
    </div>
{%endblock%}

E_Mart/Home_Module/templates/Home_Module/cart.html
{% extends 'base.html' %}
{% load static %}
{%block css%}
<link rel="stylesheet" href="{%static '/css/home/cart.css'%}"/>
{%endblock%}
{% block body %}
        {% if carts%}

        <div class="small-container cart-page">
            <div>
                <a href="{%url 'Home_Module:home'%}" class= "Cartbtn">&#x2190;Continue Shopping </a>
            </div>
            <table id="table">
                <tr>
                    <th></th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                
                </tr>
                {%for cart in carts%}
                <input type="hidden"  value={{cart.id}} > 
                <tr>
                    <td><input id="{{cart.id}}" onchange="calBill(id)" type="checkbox"/></td>
                    <td>
                        <div class="cart-info">
                            <img  src="{{cart.product.image1.url}}">
                            <div>
                                <p id="name{{cart.id}}" >{{cart.product}}</p>
                                <small id="p{{cart.id}}">Price:{{cart.product.price}}</small>
                                <a href="{%url 'Home_Module:delete_cart' cart.id%}">Remove</a>
                            </div>
                        </div>
                    </td>
                    <td><input id="qty{{cart.id}}" name={{cart.id}} onchange="calsubTotal(name)" type="number" min="1" max="{{cart.product.quantity}}" value="{{cart.qty}}"></td>
                    <p></p>
                    <td id="sub{{cart.id}}" ></td>
                </tr>
                    {%endfor%}
            </table>
             <div class="total-price">
            <table>
                <tr>
                    <td >Subtotal(<span id="noOfItems" style="font-size:16px;">0</span> items)</td>
                     <td id="sub">RS:0</td>
                </tr>
                 <tr>
                    <td>Shipping Fee</td>
                     <td>0</td>
                </tr>
                 <tr>
                    <td >Total</td>
                     <td id="total_bill">RS:0</td>
                </tr>
            </table>
        </div>
        <div class="checkout">
            <span id="checkoutError" class="error_style"></span>
            <a onclick="checkout()" class= "Cartbtn">Proceed To Checkout &rarr;
            </a>
        </div>
        </div>
        {%else%}
            <div class="container">
                <div class="logout-form">
                    <div class="paragraph" >
                        <h3>No Product is added into cart</h3>
                    </div>
                    <div>
                        <a href="{%url 'Home_Module:home'%}" class="Cartbtn " style="margin-left:130px">Continue Shopping </a>
                    </div>
                </div>
            </div> 

        {%endif%}
{% endblock %}

E_Mart/Home_Module/templates/Home_Module/change_password.html
{%extends variable%}
{%load static%}

{%block body%}
<div class="offer">
<div class="small-container">
    <div class="row">
        <div class="col-2">
            {%if not user.is_seller%}
            <img class="offer-img" src="/Images/products/images/changePass.jpg" width="100%"/>
            {%endif%}
        </div>
        <div class="col-2">
            <h1>Update Password</h1>
            <form method="POST" action="{%url 'Home_Module:update_password' user.username%}">
                {% csrf_token %}
                <div>
                    <input type="password" name="password"  id="password" onkeyup="handleResetChange(id)" onfocus="handleFocus(id)" class="txt_field" placeholder="Enter Current password"/>
                    <span id="passwordError" class="error_style"></span>
                </div>
                <div>
                    <input type="password" name="newPasswd"  id="newPassword"  onkeyup="handleResetChange(id)" onfocus="handleFocus(id)" class="txt_field" placeholder="Enter new password"/>
                    <span id="newPasswordError" class="error_style"></span>
                </div>
                <div>
                    <input type="password" name="cnfrmPassword" id="cnfrmPassword" onkeyup="handleResetChange(id)" onfocus="handleFocus(id)"  class="txt_field" placeholder="Confirm new Password" />
                    <span id="cnfrmPasswordError" class="error_style"></span>
                </div>
                <button id="resetbtn" type="submit" disabled class="Visitbtn">Update Password</button>
            </form>
             
        </div>
    </div>
</div>
</div>
{%endblock%}

E_Mart/Home_Module/templates/Home_Module/logout.html
{%extends variable %}
{% load i18n %}
{% block head_title %}{% trans "Sign Out" %}{% endblock %}
{% block body %}
  <div class="container">
  <form  class="logout-form main-div" method="post" {%if user.is_social_user%} action="/accounts/logout/" 
  {%elif user.is_seller%} action="{% url 'Home_Module:seller_logout' %}" 
  {%else%} action="{% url 'Home_Module:cust_logout' %}" {%endif%}>

  {% csrf_token %}
    <div class="heading">
      <h1>{% trans "Sign Out" %}</h1>
    </div>
    <p class="paragraph">{% trans 'Are you sure you want to sign out?' %}</p>
    {% if redirect_field_value %}
      <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
    {% endif %}
    <div class="logout-div">
      <button type="submit" class="fb_btn styling">{% trans 'Sign Out' %}</button>
      <a {%if user.is_seller%} href="{%url 'Home_Module:seller_center'%}" {%else%} href="{%url 'Home_Module:home'%}" {%endif%} class="fb_btn styling">{% trans 'Cancel' %}</a>
    </div>
    </form>
</div>
{% endblock %}

E_Mart/Home_Module/templates/Home_Module/products.html
{%extends 'base.html'%}
{%load static%}
{%block body%}
    {%if products%}
    <div class="small-container">
        <div class="row row-2">
            <h2>All Products</h2>
            
        </div>
        <div class="row">
            {%for product in products%}
            <div class="col-4">
                <p>
                    <a href="{%url 'Home_Module:productDetail' product.id%}">
                    <img src="{{product.image1.url}}">
                    </a>
                </p>
                <h4 class="productsH4">{{product.productName}}</h4>
                <div class="rating">
                    <label class="fa fa-star {% if product.averagereview >= 1 %} true-color {%else%} false-color{% endif %}"></label>
                    <label class="fa fa-star {% if product.averagereview >= 2 %} true-color {%else%} false-color{% endif %}"></label>
                    <label class="fa fa-star {% if product.averagereview >= 3 %} true-color {%else%} false-color{% endif %}"></label>
                    <label class="fa fa-star {% if product.averagereview >= 4 %} true-color {%else%} false-color{% endif %}"></label>
                    <label class="fa fa-star {% if product.averagereview >= 5 %} true-color {%else%} false-color{% endif %}"></label>
                    <p>{{product.averagereview}}</p>
                    <p>{{product.category}}</p>
                </div>
                
                <p>{{product.price}}</p>
            </div>
            {%endfor%}
        </div>
        </div>
        {%else%}
            <div class="container">
                <div class="logout-form">
                    <div class="heading">
                        <h1>OOPS!!</h1>
                    </div>
                    <div class="paragraph">
                        <h3>No Products to Show</h3>
                    </div>
                </div>
                
            
            </div>
        {%endif%}
        
{%endblock%}

E_Mart/Home_Module/templates/Home_Module/reset_password.html
{%load static%}

<html>
    <head>
        <title>Reset Password</title>
        <link rel="stylesheet" href="{%static '/css/home/reset.css'%}"/>
         <script  src="{%static  'javascript/home/SignUp.js' %}"></script>
    </head>
    <body>
        <div class="center">
            <h1>RESET PASSWORD<h1>
            <form method="POST" action="{%url 'Home_Module:reset_password_done'%}">
                {% csrf_token %}
                <div>
                    <input type="hidden" name="username" {%if username %} value={{username}} {%endif%}>
                    <input type="password" name="password"  id="newPassword"  onkeyup="handleResetChange(id)" onfocus="handleFocus(id)" class="txt_field" placeholder="Enter new password"/>
                    <span id="newPasswordError" class="error_style"></span>
                </div>
                <div>
                   <input type="password" name="cnfrmPassword" id="cnfrmPassword" onkeyup="handleResetChange(id)" onfocus="handleFocus(id)"  class="txt_field" placeholder="Confirm new Password" />
                    <span id="cnfrmPasswordError" class="error_style"></span>
                </div> 
                 <button id="resetbtn" type="submit" disabled class="submit_btn">Reset Password</button>
            </form>
        </div>
        </div>
    </body>
</html>