E_Mart/E_Mart/urls.py
from django.contrib import admin
from django.urls import path,include
from Home_Module import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home_Module.urls')),
    path('shipping/',include('shipping.urls')),
    path('order/',include('order.urls')),
    path('accounts/',include('allauth.urls')),	
    path('activate/<uidb64>/<token>',views.Verification.as_view(),name="activate"),
    path('reset_password/<uidb64>/<token>',views.reset_password,name="reset_password"),
    
   
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

E_Mart/Home_Module/urls.py
from django.urls import path
from .import views,Seller_views
from django.contrib.auth import views as auth_views
app_name='Home_Module'
urlpatterns=[
    path('',views.home,name="home"),
    path('login/', views.login,name="login"),
    path('signup/',views.signup,name="signup"),
    path('forget',views.forget,name="forget"),
    path('customer/',views.cust_api,name="cust_api"),
    path('customer/username=<str:name>',views.cust_api,name="cust_api"),
    path('customer/email=<str:email>',views.cust_api,name="cust_api"),
    path('contact',views.contact,name="contact"),
    path('productDetail/<int:id>',views.productDetail,name="productDetail"),
    path('search',views.search,name="search"),
    path('search/<str:heading>',views.search,name="search"),
    path('cart/',views.cart,name="cart"),
    path('checkout/',views.checkout,name="checkout"),
    path('logout/<str:username>',views.logout,name="account_logout"),
    path("reset_password_done",views.reset_password_done,name="reset_password_done"),
    path('update_password/<str:username>',views.change_password,name="update_password"),
    path("cust_logout",views.cust_logout,name="cust_logout"),
    path("Seller_center",Seller_views.seller_center,name="seller_center"),
    path("SellerDetail/",Seller_views.seller_detail,name="SellerDetail"),
    path("seller_logout",Seller_views.seller_logout,name="seller_logout"),
    path("add_product",Seller_views.add_product,name="add_product"),
    path('SellerDetail',Seller_views.seller_detail,name="SellerDetail"),
    path("seller_logout",Seller_views.seller_logout,name="seller_logout"),
    path('SellerDetailUpdate',Seller_views.seller_detail_update,name="SellerDetailUpdate"),
    path("edit_product/<str:pk>/",Seller_views.edit_product,name="edit_product"),
    path("delete_product/<str:pk>/",Seller_views.delete_product,name="delete_product"),
    path("delete_cart/<int:id>",views.delete_cart,name="delete_cart"),
    path("addComment/<int:id>", views.addComment,name="addComment"),
    path('reports/',Seller_views.reports,name="reports"),
    path('about/',views.about,name="about")
]

E_Mart/order/urls.py
from django.urls import path
from . import views
app_name="order"
urlpatterns=[
            path('myorders/',views.my_orders,name="my_orders"),
            path('order_details/<int:id>/',views.order_details,name="order_details"),
            path('order_delivered/<int:id>/',views.order_delivered,name="order_delivered"),
            path("orders/",views.seller_orders,name="seller_orders"),
            path('seller_order_details/<int:id>/',views.seller_orders_details,name="seller_orders_details"),
            path('seller_confirmation/<int:id>/',views.seller_confirmation,name="seller_confirmation")
]

E_Mart/shipping/urls.py
from django.urls import path
from . import views
app_name="shipping"
urlpatterns=[
            path('shipping/',views.shipping_detail,name="shipping_detail"),
            path('shipping/<str:chk>',views.shipping_detail,name="shipping_detail"),
           
        ]

E_Mart/Home_Module/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm
from Home_Module.models import ProductReview, Products
class AddProductForm(ModelForm):
    productName=forms.CharField(label="Product Name",
        widget=forms.TextInput(
            attrs={"placeholder":"Ex. Nikon Coolpix A300 Digital Camera","class":"input","autocomplete":"off"}
        )
    )
    brand=forms.CharField(label="Brand Name",
        widget=forms.TextInput(
            attrs={"placeholder":"Rolex","class":"input","autocomplete":"off"}
        )

    )
    description=forms.CharField(label="Description",required=True,
        widget=forms.Textarea(
            attrs={"autocomplete":"off","class":"input"}
        )

    )
    price=forms.CharField(label="Price",
        widget=forms.NumberInput(
            attrs={"class":"input","autocomplete":"off","min":"1"}
        )

    )
    quantity=forms.CharField(label="Quantity",
        widget=forms.NumberInput(
            attrs={"class":"input","autocomplete":"off","min":"1"}
        )

    )
    image1=forms.ImageField(
        label="Image1",required=False,
        widget=forms.FileInput(
            attrs={"class":"input","autocomplete":"off","accept":"image/*"}
        )
    )

    image2=forms.ImageField(
        label="Image2",required=False,
        widget=forms.FileInput(
            attrs={"class":"input","autocomplete":"off","accept":"image/*"}
        )
    )
    image3=forms.ImageField(
        label="Image3",required=False,
        widget=forms.FileInput(
            attrs={"class":"input","autocomplete":"off","accept":"image/*"}
        )
    )
    image4=forms.ImageField(
        label="Image4",required=False,
        widget=forms.FileInput(
            attrs={"class":"input","autocomplete":"off","accept":"image/*"}
        )
    )
 
    class Meta:
        model=Products
        exclude = ['sellerId']





    # #username=current_password=forms.HiddenInput(max_length=100,required=True,widget=forms.CharField(attrs={'hidden'}))
    # productName=forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={"placeholder":"Ex Red T-Shirt"}))
    # category=forms.CharField(max_length=100,required=True,widget=forms.Select(choices=category_choice))
    # #cnfrm_passwd=forms.CharField(max_length=100,required=True,widget=forms.PasswordInput(attrs={'placeholder':"confirm new password",'id':'cnfrm_passwd'}))
class ProductReviewForm(ModelForm):
    class Meta:
        model = ProductReview
        fields = ['subject', 'content', 'rate']

E_Mart/Home_Module/views.py
from datetime import date
from django.views import View
from django.db.models import Q
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,HttpResponseNotFound
from rest_framework.parsers import JSONParser
from django.views.decorators.csrf import csrf_exempt
from django.http.response import JsonResponse
from django import forms
from django.urls import reverse
from django.contrib import auth,messages
from django.conf import settings
from django.contrib.auth import update_session_auth_hash
from Home_Module.models import ProductReview, User,SellerDetail,Products,Cart,SellerDetail,ProductReviewForm
from order.models import Order,OrderDetails
from shipping.models import ShippingDetail
from .email_handler import token_generator,send_link
from django.utils.encoding import force_bytes,force_text,DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from .Serializer import CustomerSerializer
from .utility_functions import isUserLogin,permission_check,cart_lenght
import json
# Create your views here.

@csrf_exempt
def cust_api(request,name='',email=''):
    if request.method=="GET":
        if len(name)!=0 or len(email)!=0:
            try:
                if len(email)==0:
                    cust=User.objects.get(username=name)
                else:
                    cust=User.objects.get(email=email)
                cust_serializer=CustomerSerializer(cust)
                return JsonResponse(cust_serializer.data,safe=False)      
                
            except User.DoesNotExist:
                return JsonResponse(None,safe=False)

                              
        customers=User.objects.all()
        cust_serializer=CustomerSerializer(customers,many=True)
        return JsonResponse(cust_serializer.data,safe=False)
    
def login(request):
    if request.method=="GET":
        if "username" in request.session:
            return render(request,"Home_Module/signup.html",context={"username":request.session['username'],"password":request.session['password']})
        return render(request,"Home_Module/signup.html")
    if request.method=="POST":
        #Filtering Latest Objects on The basis of ID
        prod=Products.objects.all().order_by('-id')
        prod=prod[:4]
    
        #Filtering Featured Products
        #select_related basically works as join
        feature=ProductReview.objects.select_related('products').all().order_by('-rate')
        if len(feature)>4:
            feature=feature[:4]
        username= request.POST['username']
        password= request.POST['password']  
        cust = auth.authenticate(username=username,password=password)
   
        if cust is None:
            errorMessage="Invalid Username or Password"
        elif  not cust.is_active:
            errorMessage="Your account is not active.please check your email address"
        else: 
            
            if 'is_seller' in request.POST: #checking if the request has come from seller center or not
                if not cust.is_seller:# if request has come from seller center ,checking if user is registered as seller
                    errorMessage="you are not registered as seller"
                else:
                    if request.POST.get("remember"):
                        request.session['usernameSeller']=username
                        request.session['passwordSeller']=password
                    request.session['seller']=cust.username

                    try:                     
                        user=SellerDetail.objects.get(user=cust)
                        return HttpResponseRedirect(reverse("Home_Module:seller_center"))
                    except SellerDetail.DoesNotExist:
                        return HttpResponseRedirect(reverse("Home_Module:SellerDetail"))
            else:
                if cust.is_seller:
                    errorMessage="you are not registered as a Customer"
                else:
                    if request.POST.get("remember"):
                        request.session['username']=username
                        request.session['password']=password
                    request.session['user']=cust.username
                    cart=Cart.objects.filter(user=cust)#cart Notification
                    #context setting
                    context={"user":cust,"notify":len(cart),"Products":prod,"feature":feature}
                    return render(request,"Home_Module/Home.html",context=context)
        if "is_seller" in request.POST:
            return render(request,"Seller_Module/SellerSignUp.html",context={"errorMessage":errorMessage})
        else:
            return render(request,"Home_Module/SignUp.html",context={"errorMessage":errorMessage})
    
def home(request):
    #Filtering Latest Objects on The basis of ID
    prod=Products.objects.all().order_by('-id')
    prod=prod[:4]
    
    #Filtering Featured Products
    #select_related basically works as join
    feature=ProductReview.objects.select_related('products').all().order_by('-rate')
    if len(feature)>4:
        feature=feature[:4]
    
    user=isUserLogin(request,'user')
    if user is not None:
        cart=Cart.objects.filter(user=user)
        context={"user":user,"notify":len(cart),"Products":prod,"feature":feature}
        return render(request,"Home_Module/Home.html",context=context)
    context={"Products":prod,"feature":feature}
    return render(request,"Home_Module/Home.html",context=context)

def forget(request):
    if request.method!="POST":
        return render(request,"Home_Module/ForgetPass.html")
    else:
        email=request.POST['email']
        if len(email)==0:
            messages.error(request,"Please enter your email")   
        else:     
            try:
                user=User.objects.get(email=email,is_staff=False)
                if not user.is_active:
                    messages.warning(request,"your account is not active .please check your inbox")
                else:
                    email_subject="Reset Password"
                    email_body=f'Hey {user.username}\n You have requested a password reset.Please click the following link to  reset your password\n'
                    send_link(email_subject,email_body,user,'reset_password')
                    messages.info(request,f'Please check your inbox.we have sent an email at {user.email} for password reset')
            except User.DoesNotExist:
                messages.error(request,"No such user exist")
        return HttpResponseRedirect(reverse("Home_Module:forget"))
            
def contact(request):
    return render(request,"Home_Module/contact.html")

def search(request,heading=''):
    query=None
    if len(heading)!=0:
        query=heading
    else:
        query=request.GET['query']
    #filtering Products
    if query:
        context={"products":Products.objects.filter(productName__icontains=query)or 
        Products.objects.filter(brand__icontains=query)or Products.objects.filter(category__icontains=query)or Products.objects.filter(description__icontains=query) }
    else:
        context={}
    user=permission_check(request)
    if user is not None:
        context['user']=user
        context['notify']=cart_lenght(user)
    return render(request,"Home_Module/products.html",context=context)
    
def productDetail(request,id):
    product=Products.objects.get(pk=id)
    comments=ProductReview.objects.all().filter(products=product)
    user=permission_check(request) 
    try:
        p=ProductReview.objects.get(users=user,products=id)  
    except ProductReview.DoesNotExist:
         p = None
         print("pathan")
    if request.method=="GET":
        category=product.category
        name=product.productName
        relatedProd=Products.objects.filter(productName__icontains=name)and Products.objects.filter(category=category)
        if (len(relatedProd) >=4):
            relatedProd=relatedProd[:4]
        else:
            relatedProd=relatedProd
        context={}
        if user is not None:
            cart=Cart.objects.filter(user=user)
            context={"product":product,"comment":comments,"p":p,"user":user,"rProd":relatedProd,"notify":len(cart)}
            print("shoaib")
            return render(request,"Home_Module/productDetail.html",context=context)
           
        context={"product":product,"p":p,"comment":comments,"user":user,"rProd":relatedProd}
        return render(request,"Home_Module/productDetail.html",context=context)
    if request.method=="POST":   
        if not user in User.objects.all():
            messages.error(request,"You have to login first")
            return HttpResponseRedirect(reverse("Home_Module:signup"))
        cart=None
        try:
            cart=Cart.objects.get(user=user,product=product)
            cart.qty=cart.qty+int(request.POST['qty'])
        except Cart.DoesNotExist:
            cart=Cart.objects.create(user=user,product=product)
            cart.qty=request.POST['qty']
        cart.save()
        return HttpResponseRedirect(reverse("Home_Module:cart"))
def signup(request):
    if request.method=='GET':
        return HttpResponseRedirect(reverse("Home_Module:login"))
    
    elif request.method=='POST':
        email=request.POST['email']
        username=request.POST['username']
        password=request.POST['password'] 
        user = User.objects.create_user(username=username, email=email)
        user.set_password(password)
        user.is_active = False
        user.is_social_user=False
        if 'is_seller' in request.POST:
            user.is_seller=True
        user.save()
        email_subject="Activate your account"
        email_body=f'Hey {user.username}\n Thanks for regestring on E_Mart.We are very delighted to have you.Please click the following link to activate your account\n'
        send_link(email_subject,email_body,user,'activate')

E_Mart/Home_Module/templates/base.html
{% load static%}
{% load socialaccount %}
{% providers_media_js %}
{% load account %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>E-Mart</title>
        {%block css%}
        {%endblock%}
        <link rel="stylesheet" href="{%static '/css/home/home.css'%}"/>
        <link rel="stylesheet" href="{%static '/css/home/checkout.css'%}"/>
        <link rel="stylesheet" href="{%static '/css/home/about.css'%}"/>
        <link rel="stylesheet" type="text/css" href="style.css">
        <link rel="stylesheet" href="{%static '/css/home/changePass.css'%}"/>
        <link rel="stylesheet" href="{%static '/css/home/logout.css'%}"/>
        <link rel="stylesheet" href="{%static '/css/home/messages.css'%}"/>
        <link rel="stylesheet" href="{%static '/css/home/products.css'%}"/>
        <link rel="stylesheet" href="{%static '/css/home/payement.css'%}"/>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,400&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
       <script src="{% static 'JavaScript/home/home.js' %}"></script>
       <script  src="{%static  'javascript/home/SignUp.js' %}"></script>
       <script  src="{%static  'javascript/home/product.js' %}"></script>
       <script  src="{%static  'javascript/home/checkout.js' %}"></script>
       {%block js%}
       {%endblock%}

    
    </head>

    <body>
        <div class="header">
            <div class="wrapper">
            <nav>
                <input type="checkbox" id="show-search">
                <input type="checkbox" id="show-menu">
                <label for="show-menu" class="menu-icon"><i class="fas fa-bars"></i></label>
                <div class="content">
                    <div class="logo"><a href="">E-MART</a></div>
                    <ul class="links">
                        <li><a href="{%url 'Home_Module:home'%}"><i class="fa fa-home"></i>Home</a></li>
                        <li><a href="{%url 'Home_Module:about'%}"><i class="fas fa-info"></i>About</a></li>
                        <li><a  href="{%url 'Home_Module:seller_center'%}"><i class="fa fa-phone"></i>Sell On EMART</a></li>
                        {%if user.is_authenticated and not user.is_staff %}
                        <li><a href="" class="desktop-link" style="color:purple"><i class="fa fa-user"></i>{{user.username}}</i></a>
                            <input type="checkbox" id="show-menus">
                            <label for="show-menus"><i class="fa fa-user"></i>{{user.username}}</i></label>
                            <ul>
                                <li><a href="" /><i class="fa fa-home"></i>My Account</li>
                                <li><a href="{%url 'shipping:shipping_detail' 'base'%}" /><i class="fa fa-pencil-square" aria-hidden="true"></i>Shipping Address</li>
                                {%if not user.is_social_user%}
                                <li><a href="{%url 'Home_Module:update_password' user.username%}" /><i class="fas fa-key"></i> Update Password</li>
                                {%endif%}
                                <li><a href="{%url  'order:my_orders'%}" /><i class="fa fa-shopping-cart"></i>My Orders</li>
                                <li><a href="{%url 'Home_Module:account_logout' user.username%}" /><i class="fa fa-lock"></i>Logout</li>
                            </ul>
                        </li>
                        <li><a href="{%url 'Home_Module:cart'%}"><i class="fa fa-shopping-cart"><span class="icon-badage">{{notify}}</span></i>Cart</a></li>
                        {%else%}
                        <li><a href="{%url 'Home_Module:signup'%}"/><i class="fas fa-unlock-alt"></i>Login</li>
                        <li><a href="{%url 'Home_Module:cart'%}"><i class="fa fa-shopping-cart"><span class="icon-badage"></span></i>Cart</a></li>
                        {%endif%}
                        
                    </ul>
                </div>
                <label for="show-search" class="search-icon"><i class="fas fa-search"></i></label>
                <form class="search-box" Method="GET" action="{%url 'Home_Module:search'%}">
                    <input type="text" placeholder="Type Something to Search..." name="query">
                    <button class="go-icon" type="submit"><i class="fas fa-long-arrow-alt-right fa-lg"></i></button>
                </form>
                </nav>
            </div>
        </div>
        {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </div>
        {% endfor %}
        {%block body%}
        {%endblock%}
        <!-----------------Brands-------------->
        <div class="brands">
            <div class="small-container">
                <div class="row">
                    <div class="col-5">
                        <img src="/Images/products/images/logo-godrej.png"/>
                    </div>
                    <div class="col-5">
                        <img src="/Images/products/images/logo-oppo.png"/>
                    </div>
                    <div class="col-5">
                        <img src="/Images/products/images/logo-coca-cola.png"/>
                    </div>
                    <div class="col-5">
                        <img src="/Images/products/images/logo-paypal.png"/>
                    </div>
                    <div class="col-5">
                        <img src="/Images/products/images/logo-philips.png"/>
                    </div>
                </div>
            </div>
        </div>
      
<!------------------------FOOTER-------------------->
            <footer>
                <div class="main-content">
                    <div class="left box">
                        <h2>About Us</h2>
                        <div class="content">
                            <p class="text">EMART is one of the best E-commerce website, with help of which you
                            can sale or purchase high quality products with ease.</p>
                        </div>
                        <div class="social">
                            <a href="" ><span class="fab fa-facebook-f"></span></a>
                            <a href="" ><span class="fab fa-instagram"></span></a>
                            <a href="" ><span class="fab fa-twitter"></span></a>
                        
                        </div>
                    </div>
                    <div class="center-box box">
                    <h2>Address</h2>
                    <div class="content">
                        <div class="place">
                            <span class="fas fa-map-marker-alt"></span>
                            <span class="text">University of Punjab, Anarkali Main Market.</spna>
                        
                        </div>
                        <div class="phone">
                            <span class="fas fa-phone"></span>
                            <span class="text">0900-78601 Telephone</spna>
                        
                        </div>
                        <div class="email">
                            <span class="fas fa-envelope"></span>
                            <span class="text">eMart1234@gmail.com</spna>
                        
                        </div>
                    </div>
                </div>
                <div class="right box">
                    <h2>Contact Us</h2>
                    <div class="content">
                        <form action="#">
                            <div class="email">
                                <div class="text">Email*</div>
                                <input type="email" required />
                            </div>
                            <div class="message">
                                <div class="text">Message*</div>
                                <textarea rows="2" cols="25" required></textarea>
                            </div>
                            <div>
                                <button class="Visitbtn"type="submit">Send</button>
                            </div>
                            
                        </form>
                    </div>
                </div>
                </div>
                <hr>
                <p class="copyright">&#169; Copyroght 2021-EMART.com</p>
            </footer>
        </body>
</html>